# Multi-Stage Dockerfile
# Stage 1: builder image
FROM python:3.11-slim as builder

WORKDIR /build

COPY requirements.txt .

RUN pip install --user --no-cache-dir -r requirements.txt




#----
#----
# Stage 2: production image
FROM python:3.11-slim

WORKDIR /app

# only copy the installed libraries from the builder stage to keep the final image small
COPY --from=builder /root/.local /root/.local
COPY app.py .

# Update PATH
ENV PATH=/root/.local/bin:$PATH

EXPOSE 5000

CMD ["python", "app.py"]